# Generated by Django 5.2.17 on 2026-10-09 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'adjacencies',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='games.game')),
                ('neighbors', models.ManyToManyField(blank=True, through='territories.Adjacency', through_fields=('from_territory', 'to_territory'), to='territories.territory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='games.gameplayer')),
            ],
            options={
                'verbose_name_plural': 'territories',
                'ordering': ['game_id', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)])),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='games.gameplayer')),
                ('territory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='territories.territory')),
            ],
            options={
                'ordering': ['territory__game_id', 'player__player_order'],
            },
        ),
        migrations.AddField(
            model_name='adjacency',
            name='from_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='territories.territory'),
        ),
        migrations.AddField(
            model_name='adjacency',
            name='to_territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='territories.territory'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='territories_territory_game_name_unique', violation_error_message='A territory with this name already exists in the game.'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('game', 'slug'), name='territories_territory_game_slug_unique', violation_error_message='A territory with this slug already exists in the game.'),
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.CheckConstraint(condition=models.Q(('health__lte', 3)), name='territories_capital_health_max', violation_error_message='Capital health cannot exceed 3.'),
        ),
        migrations.AddConstraint(
            model_name='adjacency',
            constraint=models.UniqueConstraint(fields=('from_territory', 'to_territory'), name='territories_adjacency_pair_unique', violation_error_message='These territories are already neighbours.'),
        ),
        migrations.AddConstraint(
            model_name='adjacency',
            constraint=models.CheckConstraint(condition=models.Q(('from_territory', models.F('to_territory')), _negated=True), name='territories_adjacency_not_self', violation_error_message='A territory cannot border itself.'),
        ),
    ]
